# Generated by Django 5.2.7 on 2025-11-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0002_bloco_criador_por_curso_criador_por_sala_criador_por_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="id_bloco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="salas.bloco",
                verbose_name="Bloco",
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="numero_sala",
            field=models.IntegerField(verbose_name="Número da sala"),
        ),
        migrations.AlterField(
            model_name="sala",
            name="tv_tamanho",
            field=models.CharField(max_length=5, verbose_name="Tamanho da TV"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="codigo_turma",
            field=models.CharField(max_length=255, verbose_name="Código da turma"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="id_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salas.curso",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="quantidade_aluno",
            field=models.IntegerField(null=True, verbose_name="Quantidade de alunos"),
        ),
    ]
