# Generated by Django 5.2.7 on 2025-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0003_alter_sala_id_bloco_alter_sala_numero_sala_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="andar",
            field=models.CharField(max_length=50),
        ),
    ]
