# Generated by Django 5.2.7 on 2025-11-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0004_alter_sala_andar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="tv_tamanho",
            field=models.CharField(
                max_length=5, null=True, verbose_name="Tamanho da TV"
            ),
        ),
    ]
