# Generated by Django 5.2.7 on 2025-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0005_alter_sala_tv_tamanho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="tv_tamanho",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Tamanho da TV"
            ),
        ),
    ]
