# Generated by Django 5.2.7 on 2025-10-26 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="criador_por_matricula",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_criados",
                to=settings.AUTH_USER_MODEL,
                to_field="matricula",
            ),
        ),
    ]
