# Generated by Django 5.2.7 on 2025-10-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_criado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="matricula",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
