# Generated by Django 5.2.7 on 2025-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Membro da Equipe"),
        ),
    ]
