# Generated by Django 5.2.7 on 2025-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_usuario_is_active_alter_usuario_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Diretor", "Diretor"),
                    ("Assessora Administrativa", "Assessora Administrativa"),
                    (
                        "Núcleo de Tecnologia e Informação",
                        "Núcleo de Tecnologia e Informação",
                    ),
                    ("Coordenador", "Coordenador"),
                    ("ecretário", "Secretário"),
                    (
                        "Núcleo de Apoio Psicopedagógico",
                        "Núcleo de Apoio Psicopedagógico",
                    ),
                    ("Manutenção", "Manutenção"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de nascimento"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se este usuário deve ser tratado como ativo.",
                verbose_name="Ativo",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o usuário pode acessar este site de administração.",
                verbose_name="Membro da Equipe",
            ),
        ),
    ]
