# Generated by Django 5.2.7 on 2025-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_usuario_cargo_alter_usuario_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Diretor", "Diretor"),
                    ("Assessora Administrativa", "Assessora Administrativa"),
                    (
                        "Núcleo de Tecnologia e Informação",
                        "Núcleo de Tecnologia e Informação",
                    ),
                    ("Coordenador", "Coordenador"),
                    ("Secretário", "Secretário"),
                    (
                        "Núcleo de Apoio Psicopedagógico",
                        "Núcleo de Apoio Psicopedagógico",
                    ),
                    ("Manutenção", "Manutenção"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                    ("Outro", "Outro"),
                    ("Prefiro não informar", "Prefiro não informar"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
