# Generated by Django 5.2.7 on 2025-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_alter_usuario_cargo_alter_usuario_sexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="matricula",
            field=models.CharField(max_length=6, unique=True, verbose_name="Matrícula"),
        ),
    ]
