# Generated by Django 5.2.7 on 2025-10-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_turma", models.CharField(max_length=255)),
                ("data_inicial", models.DateField(blank=True, null=True)),
                ("data_final", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="salas.curso",
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salas.turma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turno", models.CharField(max_length=255)),
                ("responsavel", models.CharField(max_length=255)),
                ("descricao_reserva", models.TextField()),
                ("status_reserva", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reservas.reserva",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="salas.sala",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primeiro", models.BooleanField(default=False)),
                ("segundo", models.BooleanField(default=False)),
                ("terceiro", models.BooleanField(default=False)),
                ("quarto", models.BooleanField(default=False)),
                ("integral", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_reservasala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reservas.reservasala",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaSemana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segunda", models.BooleanField(default=False)),
                ("terca", models.BooleanField(default=False)),
                ("quarta", models.BooleanField(default=False)),
                ("quinta", models.BooleanField(default=False)),
                ("sexta", models.BooleanField(default=False)),
                ("sabado", models.BooleanField(default=False)),
                ("domingo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reservas.periodo",
                    ),
                ),
                (
                    "id_reservasala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reservas.reservasala",
                    ),
                ),
            ],
        ),
    ]
