# Generated by Django 5.2.7 on 2025-11-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_reserva_criador_por"),
        ("salas", "0003_alter_sala_id_bloco_alter_sala_numero_sala_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diasemana",
            name="domingo",
            field=models.BooleanField(default=False, verbose_name="Domingo"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="id_periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reservas.periodo",
                verbose_name="Período",
            ),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="id_reservasala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reservas.reservasala",
                verbose_name="Sala reservada",
            ),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="quarta",
            field=models.BooleanField(default=False, verbose_name="Quarta-feira"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="quinta",
            field=models.BooleanField(default=False, verbose_name="Quinta-feira"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="sabado",
            field=models.BooleanField(default=False, verbose_name="Sábado"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="segunda",
            field=models.BooleanField(default=False, verbose_name="Segunda-feira"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="sexta",
            field=models.BooleanField(default=False, verbose_name="Sexta-feira"),
        ),
        migrations.AlterField(
            model_name="diasemana",
            name="terca",
            field=models.BooleanField(default=False, verbose_name="Terça-feira"),
        ),
        migrations.AlterField(
            model_name="periodo",
            name="id_reservasala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reservas.reservasala",
                verbose_name="Sala reservada",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="codigo_turma",
            field=models.CharField(max_length=255, verbose_name="Código da turma"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="id_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salas.curso",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="id_turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="salas.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="reservasala",
            name="descricao_reserva",
            field=models.TextField(verbose_name="Descrição da reserva"),
        ),
        migrations.AlterField(
            model_name="reservasala",
            name="id_reserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reservas.reserva",
                verbose_name="Reserva",
            ),
        ),
        migrations.AlterField(
            model_name="reservasala",
            name="id_sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="salas.sala",
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="reservasala",
            name="responsavel",
            field=models.CharField(max_length=255, verbose_name="Responsável"),
        ),
        migrations.AlterField(
            model_name="reservasala",
            name="status_reserva",
            field=models.BooleanField(default=True, verbose_name="Status da reserva"),
        ),
    ]
