# Generated by Django 5.2.7 on 2025-11-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservas",
            "0003_alter_diasemana_domingo_alter_diasemana_id_periodo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservasala",
            name="turno",
            field=models.CharField(
                choices=[
                    ("Matutino", "Matutino"),
                    ("Vespertino", "Vespertino"),
                    ("Noturno", "Noturno"),
                ],
                max_length=15,
            ),
        ),
    ]
