# Generated by Django 5.2.7 on 2025-11-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0004_alter_reservasala_turno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodo",
            name="id_reservasala",
        ),
        migrations.CreateModel(
            name="HorarioOcupado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "periodo",
                    models.IntegerField(
                        choices=[
                            (1, "1º Período"),
                            (2, "2º Período"),
                            (3, "3º Período"),
                            (4, "4º Período"),
                        ]
                    ),
                ),
                (
                    "reserva_sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="reservas.reservasala",
                    ),
                ),
            ],
            options={
                "unique_together": {("reserva_sala", "dia_semana", "periodo")},
            },
        ),
        migrations.DeleteModel(
            name="DiaSemana",
        ),
        migrations.DeleteModel(
            name="Periodo",
        ),
    ]
